### ISSUE TITLE
VimRC plugin broken

### ISSUE THREAD

**Issue by ianTevesAcc** [esm7/obsidian-vimrc-support#221]
**Please Review Before Posting!**

- [x] I checked that the bug *does not happen* in the [CodeMirror Vim demo](https://codemirror-vim--util.repl.co/). If it does, please report it [there](https://github.com/replit/codemirror-vim) and not here.
- [x] I'm reasonably sure that this bug is indeed about the Vimrc file support and not a general Vim in Obsidian issue. If it's a general Vim issue, report it [here](https://forum.obsidian.md/c/bug-reports/7).

**Describe the bug:**
It just doesn't work anymore. I made a new obsidian vault and also tried turned off every plug in except vimrc support, but the vimrc support plugin doesn't work. All I know is that it's producing this error.

It worked fine before but I just noticed that it's suddenly stopped working. Maybe it's because of the new OB update that I just noticed has affected vimrc support plugin.

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'off')
    at VimrcPlugin.eval (main.ts:152:13)
    at step (tslib.es6.js:100:23)
    at Object.eval [as next] (tslib.es6.js:81:53)
    at eval (tslib.es6.js:74:71)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70:12)
    at VimrcPlugin.updateVimEvents (main.ts:141:2)
    at VimrcPlugin.eval (main.ts:103:9)
    at step (tslib.es6.js:100:23)
    at Object.eval [as next] (tslib.es6.js:81:53)

**Environment (please complete the following information):**
 - OS: 
 Device name	Ian_Teves
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Installed RAM	16.0 GB (15.8 GB usable)
Device ID	8C34DDB7-B928-4BF7-8648-819AA3203118
Product ID	00342-21968-87127-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support
 - Vimrc plugin version: Version 0.9.0

**Comment by ianTevesAcc** [comment]
Idk what happened... 
I didn't restart my computer, I just continued with my day and it fixed itself.
Anyways. It works now. Sorry for the hassle
